# 1. THE DEPLOYMENT: Running the Python API containers
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2 # High Availability: Kubernetes will balance traffic between two identical copies
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          # REPLACE 'YOUR_DOCKERHUB_USERNAME' with your actual Docker Hub username
          image: vivekovhal/task-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            # Tell the Python code to look for the database service named 'db'
            - name: DB_HOST
              value: "db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB
        
        # New Probe Configuration to make the applicatoin more resilient.
          livenessProbe:
            httpGet:
              path: /tasks
              port: 5000
            initialDelaySeconds: 15       # Wait 15 seconds before the first check to let the app boot up
            periodSeconds: 10             # Check every 10 seconds
            failureThreshold: 3           # Restart the container if it fails 3 times in a row
          
          readinessProbe:
            httpGet:
              path: /tasks
              port: 5000
            initialDelaySeconds: 5        # Start checking after 5 seconds
            periodSeconds: 5              # Check every 5 seconds


---
# 2. THE SERVICE: Exposing the application to your local machine
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort  # Exposes the service on a specific port of the cluster node
  selector:
    app: task-api
  ports:
    - protocol: TCP
      port: 5000        # The port the service listens on internally
      targetPort: 5000  # The port inside the container
      nodePort: 30007   # The port opened on your local machine to access the app

