apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
# stringData allows us to write plain text, which Kubernetes will automatically encode for us
stringData:
  POSTGRES_USER: devops
  POSTGRES_PASSWORD: supersecret
  POSTGRES_DB: taskdb
  
